### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by ahuang11**
Missing a ton of functions documentation because of lack of docstrings, but this sets up the docs infrastructure. Also add developer packages

image

### CODE REVIEW

**Comment by chadhutchins182** [comment]
@ahuang11 did this get fixed by something else? It's on my todo list just a lot has been taking my time.

**Comment by ahuang11** [comment]
Oh, I was cleaning my inbox of stale PRs; thought you had something else in mind, e.g. sphinx

**Comment by chadhutchins182** [comment]
I'll wait for @mindyls to look at it, if she is cool with it I'll merge

**Review by mindyls — APPROVED** [review]
Looks good to me! Sorry for the delay!

**Pull request merged**
