### PR TITLE
3 upload package to pypi

### LINKED ISSUE #3: Upload package to pypi
so that `pip install xnrl` works

### PR DESCRIPTION
**Pull request by chadhutchins182**
This addresses and will close #3 

I've tested it here: https://test.pypi.org/project/xnrl/2022.6.13.5/

Using this action job: https://github.com/U-S-NRL-Marine-Meteorology-Division/xnrl/actions/runs/3132481612/jobs/5084872587

This is triggered by any tag pushed, need to make sure only owners can push tags (should be that way already)

### CODE REVIEW

**Comment by mindyls** [comment]
@chadhutchins182 Maybe my join(dirname(realpath(__file__)), 'VERSION') needs to be replaced with:

```
from pathlib import Path
this_directory = Path(__file__).parent
version_file = (this_directory / "VERSION").read_text()
```

It failed when I tried to pip install as is:
```
 > pip install -i https://test.pypi.org/simple/ xnrl==2022.6.13.5

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sid19yz5/xnrl_6daae7f988d74f14acd930a78a1688d7/setup.py", line 23, in <module>
          with open(join(dirname(realpath(__file__)), 'VERSION'), encoding='utf-8') as version_file:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-sid19yz5/xnrl_6daae7f988d74f14acd930a78a1688d7/VERSION'
```

**Comment by chadhutchins182** [comment]
I took the read_text() from https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

I figured if it made it t pypi that it was ok. I've only done npm modules not python modules before. 

@ahuang11 any ideas?

**Comment by ahuang11** [comment]
Maybe need to include in MANIFEST.in?

**Comment by chadhutchins182** [comment]
Ok I switched to ```from distutils.core import setup```

That produced a MANIFEST file.

But https://test.pypi.org/project/xnrl/2022.9.27.2/ I don't think it still works.

**Comment by chadhutchins182** [comment]
Anyone notice anything in the last log? https://pipelines.actions.githubusercontent.com/serviceHosts/d681d618-32c1-4d6d-8104-b39921bcf7fc/_apis/pipelines/1/runs/15/signedlogcontent/2?urlExpires=2022-09-27T19%3A56%3A41.6542282Z&urlSigningMethod=HMACV1&urlSignature=eV0haM6%2F3x2wwOY3RpGkG4TtDJj2n8AjgqKrxCMqTEg%3D

**Comment by chadhutchins182** [comment]
Actual Latest: https://test.pypi.org/project/xnrl/2022.9.27.3/

Log: https://pipelines.actions.githubusercontent.com/serviceHosts/d681d618-32c1-4d6d-8104-b39921bcf7fc/_apis/pipelines/1/runs/16/signedlogcontent/2?urlExpires=2022-09-27T20%3A05%3A13.7223683Z&urlSigningMethod=HMACV1&urlSignature=ELB%2BgCe%2FOtXMvAuS1od2oxoLyKdxqgMz3ZlhEU%2FlhXc%3D

**Comment by mindyls** [comment]
Now it can't find a matching version:

bash$ pip install -i https://test.pypi.org/simple/ xnrl==2022.9.27.3
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement xnrl==2022.9.27.3 (from versions: 2022.6.13.3, 2022.6.13.4, 2022.6.13.5)
ERROR: No matching distribution found for xnrl==2022.9.27.3

**Comment by chadhutchins182** [comment]
> Now it can't find a matching version:
> 
> bash$ pip install -i https://test.pypi.org/simple/ xnrl==2022.9.27.3 Looking in indexes: https://test.pypi.org/simple/ ERROR: Could not find a version that satisfies the requirement xnrl==2022.9.27.3 (from versions: 2022.6.13.3, 2022.6.13.4, 2022.6.13.5) ERROR: No matching distribution found for xnrl==2022.9.27.3

@mindyls Try 5

https://test.pypi.org/project/xnrl/2022.6.13.5/

**Comment by mindyls** [comment]
> > Now it can't find a matching version:
> > bash$ pip install -i https://test.pypi.org/simple/ xnrl==2022.9.27.3 Looking in indexes: https://test.pypi.org/simple/ ERROR: Could not find a version that satisfies the requirement xnrl==2022.9.27.3 (from versions: 2022.6.13.3, 2022.6.13.4, 2022.6.13.5) ERROR: No matching distribution found for xnrl==2022.9.27.3
> 
> @mindyls Try 5
> 
> https://test.pypi.org/project/xnrl/2022.6.13.5/

Still doesnt find VERSION.

      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-e7c253en/xnrl_f459ea76d30b49fa99cedcbbb6496f08/VERSION'
      [end of output]

**Comment by ahuang11** [comment]
I mean create a MANIFEST.in file similar to
https://github.com/PrefectHQ/prefect-dask/blob/main/MANIFEST.in

**Comment by chadhutchins182** [comment]
I think I still see the same problem: https://test.pypi.org/project/xnrl/2022.9.27.5/ 

Log File shows the VERSION file making it in: https://pipelines.actions.githubusercontent.com/serviceHosts/d681d618-32c1-4d6d-8104-b39921bcf7fc/_apis/pipelines/1/runs/18/signedlogcontent/2?urlExpires=2022-09-27T23%3A35%3A20.3286166Z&urlSigningMethod=HMACV1&urlSignature=1t0ff4vn8TKbfRf0jktRH%2BT4XUVDPK0miApSnMi3vHg%3D

**Comment by chadhutchins182** [comment]
Please check https://test.pypi.org/project/xnrl/2022.9.27.6/

Thanks to @jacobgull

Also this now relates to #5

**Comment by mindyls** [comment]
> Please check https://test.pypi.org/project/xnrl/2022.9.27.6/
> 
> Thanks to @jacobgull
> 
> Also this now relates to #5

```
bash$ pip install -i https://test.pypi.org/simple/ xnrl==2022.9.27.6
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement xnrl==2022.9.27.6 (from versions: 2022.6.13.3, 2022.6.13.4, 2022.6.13.5, 2022.9.27.1, 2022.9.27.2, 2022.9.27.3, 2022.9.27.4, 2022.9.27.5)
ERROR: No matching distribution found for xnrl==2022.9.27.6
```
Maybe that means it is reading the VERSION file successfully, but it is not recognizing the version that is set in setup.py?

Also - are we sure we need to hold xarray to 0.16.2?  Forcing 0.16.2 will force a lot of other packages to older versions as well.

**Comment by chadhutchins182** [comment]
@mindyls at first I had removed the version specification just like our local copy, but talking with @jacobgull I might needed to still specify it.

I'm not sure what to do honestly.

**Comment by mindyls** [comment]
> @mindyls at first I had removed the version specification just like our local copy, but talking with @jacobgull I might needed to still specify it.
> 
> I'm not sure what to do honestly.

Hmm, 2022.9.27.5 actually worked (but then xarray==0.16.2 failed - python 3.9.13 couldn't find anything less than 0.17.0....)

**Comment by chadhutchins182** [comment]
Well I think making sure @jacobgull 's update on our side for the xarray version is up here. Then I think I can remove the version requirement for xarray. He just messaged me and said that change isn't up here, I'll work on that now as well.

**Comment by mindyls** [comment]
> Well I think making sure @jacobgull 's update on our side for the xarray version is up here. Then I think I can remove the version requirement for xarray. He just messaged me and said that change isn't up here, I'll work on that now as well.

Do it!

**Comment by chadhutchins182** [comment]
Let's all try: https://test.pypi.org/project/xnrl/2022.9.27.8/

Which now includes #6

**Comment by chadhutchins182** [comment]
@mindyls I was able to get that version to install after I upgraded my version of pip on my system

**Review by mindyls — APPROVED** [review]
It worked!  So it is just the MANIFEST.in, publish-to-pypi.yml, and updates to setup.py (plus setting up the pipeline) to get it to work?

**Comment by chadhutchins182** [comment]
> It worked!  So it is just the MANIFEST.in, publish-to-pypi.yml, and updates to setup.py (plus setting up the pipeline) to get it to work?

It required Jacob's updates as well for xarray. 

Let me update the action to use regular PiPY and only on tags then  it will be ready for main.

**Comment by chadhutchins182** [comment]
This should be ready to go for regular PyPI. I'm going to merge and close.

Closes #3 #5 #6

**Pull request merged**
